[package]
name = "aswmake"
version = "0.1.0"
edition = "2024"

[dependencies]
aswmake-lib = { path = "./aswmake-lib" }
color-print = "0.3.7"
clap = { version = "4.6.1", features = ["derive"] }
confy = "2.0.0"
directories = "6.0.0"
dotenvy = "0.15.7"
include_dir = { version = "0.7.4", features = ["glob"] }
inquire = "0.9.4"
toml = "1.1.2"

anyhow = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
path-clean = { workspace = true }
walkdir = { workspace = true }
lazy-regex = { workspace = true }
suitest = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }

[workspace]
exclude = [
    "aswmake-lib/external/bbscript",
    "aswmake-lib/external/bbspack",
    "aswmake-lib/external/u4pak"
]

[workspace.dependencies]
anyhow = "1.0.102"
strum = { version = "0.28.0", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
path-clean = "1.0.1"
walkdir = "2.5.0"
lazy-regex = "3.6.0"
suitest = "0.1.4"
itertools = "0.14.0"
rayon = "1.12.0"
