[tasks.build_external]
script = [
    "RUSTFLAGS='-A warnings' cargo build --release --manifest-path external/bbscript/Cargo.toml",
    "RUSTFLAGS='-A warnings' cargo build --release --manifest-path external/bbspack/Cargo.toml",
    "RUSTFLAGS='-A warnings' cargo build --release --manifest-path external/u4pak/Cargo.toml",
]

[tasks.build]
dependencies = ["build_external"]

[tasks.run]
dependencies = ["build_external"]
command = "cargo"
args = ["run"]

[tasks.test]
description = "Guarantees the mocks exist before running the tests"
dependencies = ["build_external"]
env = { "FIXTURES_DIR" = "${CARGO_MAKE_WORKING_DIRECTORY}/target/fixtures" }
command = "cargo"
args = ["test", "-p", "aswmake", "--lib", "--", "--nocapture"]
