[env]
BBSPACK_EXE = "external/bbspack/target/release/bbspack"
BBSCRIPT_EXE = "external/bbscript/target/release/bbscript"
U4PAK_EXE = "external/u4pak/target/release/u4pak"
QUICKBMS_EXE = "external/quickbms/quickbms_4gb_files"
